kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: readers-cr
    namespace: readers
rules:
  - apiGroups: [""]
    resources: ["pods","nodes","services"]
    verbs: ["get","list", "watch"] 

